services:
  navigation-app:
    build: .
    command: >
      flask --app src/server run --debug --host 0.0.0.0
       --port 9800 --cert=/ssl/cert.pem --key=/ssl/key.pem
    volumes:
      - ./:/code
    ports:
      - 9800:9800 # Flask server
      - 8889:8889 # Jupyter notebook