services:
  navigation-app:
    build: .
    command: flask --app src/server run --host 0.0.0.0 --port 9800
    volumes:
      - ./:/code
    ports:
      - 9800:9800 # Flask server
      - 8889:8889 # Jupyter notebook